# Generated by Django 5.2.8 on 2025-11-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210503_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_update',
            field=models.BooleanField(
                default=True,
                help_text='Enable user profile updating for local user.',
            ),
        ),
    ]
